
FPS = 60
ROAD_GRID_SIZE = 100
ROAD_COLS = 11
ROAD_ROWS = 6
MOWER_SPACE = 70

MOWER_WIDTH = 64
MOWER_HEIGHT = 64
NUMBER_OF_MOWERS = 6

ENERGY_SPACE = 100
CARD_WIDTH, CARD_HEIGHT = 90, ROAD_GRID_SIZE
MAX_CARD_AMOUNT = 10

SCREEN_WIDTH = ROAD_GRID_SIZE * ROAD_COLS + MOWER_SPACE
SCREEN_HEIGHT = ROAD_GRID_SIZE * (ROAD_ROWS + 1)

SELECT_ZONE = ROAD_GRID_SIZE * 4


EDITOR_SCREEN_SIZE = (SCREEN_WIDTH + SELECT_ZONE, SCREEN_HEIGHT)
EDITOR_COLS = 50
MAP_WIDTH = MOWER_SPACE + ROAD_GRID_SIZE * EDITOR_COLS


SEED_PACKET_SIZE = 40
SEED_PACKET_WIDTH = SEED_PACKET_SIZE
SEED_PACKET_HEIGHT = SEED_PACKET_SIZE

GROUND_COLOR = (235, 230, 164)
GRASS_COLOR = (112, 192, 72)
LINE_COLOR = (239, 191, 4)
ZOMBIE_COLOR = (133, 168, 91)

ZOMBIE_SPAWN_COL = 17

# zombies appears corresponding to map/level
ZOMBIES_APPEARS = {'map0': {'zombie_1': 0.7, 'zombie_2': 0.3}}

DAMAGE_PLANTS = {'PeaShooter': 10, 'ThornyNut': 10}
DAMAGE_ZOMBIES = {'Zombie_1': 10, 'Zombie_2': 30}




