
FPS = 60
ROAD_GRID_SIZE = 120
ROAD_GRID_SIZE = 100
ROAD_COLS = 11
ROAD_ROWS = 6
MOWER_SPACE = 70
ENERGY_SPACE = 100
CARD_WIDTH, CARD_HEIGHT = 100, ROAD_GRID_SIZE
MAX_CARD_AMOUNT = 10

SCREEN_WIDTH = ROAD_GRID_SIZE * ROAD_COLS + MOWER_SPACE
SCREEN_HEIGHT = ROAD_GRID_SIZE * (ROAD_ROWS + 1)

GRASS_COLOR = (112, 192, 72)
LINE_COLOR = (239, 191, 4)

ZOMBIE_SPAWN_COL = 17

# zombies appears corresponding to map/level
ZOMBIES_APPEARS = {'map0': {'zombie_1': 0.7, 'zombie_2': 0.3}}



